name: "CI-CD Workflow"
on:
  push:
    branches:
      - master
      

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Copy dist to VPS
      uses: appleboy/scp-action@v0.1.7
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.SSH_KEY }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "."
        target: "~/laravel_technical_test"
    - name: Install and start application
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/laravel_technical_test
          cp .env.example .env
          chmod +x run.sh
          ./run.sh
          cp ~/laravel_technical_test /var/www/html/laravel_technical_test
          
